const styles = {
    loginContainer: {
        height: "100vh",
        width: "100vw",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: 'column',
    },
    loginFormContainer: {
        padding: "1rem",
        border: "1px solid #c0c0c0",
        backgroundColor: "white",
        width: "20rem",
        borderRadius: "10px",
        display: "flex",
        alignItems: "center",
        flexDirection: "column",
        boxSizing: 'border-box',
    },
    loginTitle: {
        margin: 30,
        fontSize: 24,
        fontWeight: "normal",
    },
    loginForm: {
        margin: 0,
        padding: 0,
        width: '100%',
    },
    toggleButton: {
        border: '1px solid black',
        padding: "1rem",
        backgroundColor: "#abcdff",
        width: "20rem",
        marginTop: 20,
        borderRadius: 12,
        fontSize: 18,
        alignItems: 'center',
        justifyContent: 'center',
        display: 'flex',
        cursor: 'pointer',
    },
};
export default styles;